# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9587fbc6c85c2458256703d434e3f460d269868d7a8763678c2e1c533708ebf26cc47c007071194bbd56f7f1494d711993cf1d763dbd9167ef5c00217a8203e6

test:
  secret_key_base: 617a27ff1e31d849c660eae4a7aa2b004ea722111788662bfb5b23352c531f612944403da4af457a359db9f36e1562dfb1dc601a9b9f5a1ecee658fb9841b17e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
